language: python
env:
    - TOX_ENV=py35
python: 3.5
script: travis_wait tox -e $TOX_ENV
install: pip install tox
addons:
    apt:
        packages:
            - python3-dev
            - imagemagick
